/**
 * Generated by FITpro Fixture Generator
 */
package Fixtures;

import org.orm.PersistentException;
import org.orm.PersistentSession;
import org.orm.PersistentTransaction;

import fit.ActionFixture;
import good_reading.Book;


/*
 * TODO: modify class to match the FIT test - edit and add methods as required.
 */
public class AddNewBook extends ActionFixture {

	Book book;
    int bid;
    
	public void creatNewBook() {
		// TODO Auto-generated method stub
		book = controllers.DatabaseManagementController.AddBook();
		bid = book.get_bid();
	}
  
    
	public Boolean getBook() {
		// TODO Auto-generated method stub
		try {
			if(Book.getBookByORMID(bid)==null)return false;
		} catch (PersistentException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return true;
	}
  
    
	public void saveBookInDatabase() {
		// TODO Auto-generated method stub
		controllers.DatabaseManagementController.EditBook(book);	
	}
  
    
	public void setLanguage(String setLanguage) {
		// TODO Auto-generated method stub
		book.set_language(setLanguage);
	}
  
    
	public void setPrice(float setPrice) {
		// TODO Auto-generated method stub
		book.set_price(setPrice);
	}
  
    
	public void setTitle(String setTitle) {
		// TODO Auto-generated method stub
		book.set_title(setTitle);
	}
  
    
	public void setViewCatalog(String setViewCatalog) {
		// TODO Auto-generated method stub
		if(setViewCatalog.equals("true"))book.set_viewStatus(true);
		else book.set_viewStatus(false);
			
	}
  

}

