/**
 * Generated by FITpro Fixture Generator
 */
package Fixtures;

import fit.ActionFixture;

/*
 * TODO: modify class to match the FIT test - edit and add methods as required.
 */
public class SubmitReview extends ActionFixture {


    
	public String getName() {
		// TODO Auto-generated method stub
		return null;
	}
  
    
	public void initialize() {
		// TODO Auto-generated method stub
	}
  

}

